# Generated by Django 4.2.16 on 2024-11-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=10)),
                ("street_name", models.CharField(max_length=100)),
                (
                    "apartment_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("zip_code", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("date_of_registration", models.DateField()),
                (
                    "party_affiliation",
                    models.CharField(
                        help_text="Political party affiliation", max_length=50
                    ),
                ),
                ("precinct_number", models.CharField(max_length=20)),
                (
                    "v20_state",
                    models.BooleanField(
                        default=False, help_text="Voted in 2020 State Election"
                    ),
                ),
                (
                    "v21_town",
                    models.BooleanField(
                        default=False, help_text="Voted in 2021 Town Election"
                    ),
                ),
                (
                    "v21_primary",
                    models.BooleanField(
                        default=False, help_text="Voted in 2021 Primary Election"
                    ),
                ),
                (
                    "v22_general",
                    models.BooleanField(
                        default=False, help_text="Voted in 2022 General Election"
                    ),
                ),
                (
                    "v23_town",
                    models.BooleanField(
                        default=False, help_text="Voted in 2023 Town Election"
                    ),
                ),
                (
                    "voter_score",
                    models.IntegerField(
                        help_text="Number of past 5 elections the voter participated in"
                    ),
                ),
            ],
        ),
    ]
