# Generated by Django 4.2.16 on 2024-12-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryitem",
            name="day",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="itineraryitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="itineraryitem",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="itineraryitem",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
