# Generated by Django 4.2.16 on 2024-10-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="city", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
